name: bucca_king
description: A professional food ordering app for BuccaKing Restaurant
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ui & Navigation
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3

  # Firebase
  firebase_core: ^2.24.2 
  firebase_auth:  ^4.16.0  
  cloud_firestore: ^4.14.0 
  firebase_messaging: ^14.7.10

  # Persisted storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/