// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4FsP2k62piKAlu0LyISJNslz61QidKYw',
    appId: '1:176626384167:web:a31fa15850834235dfbd02',
    messagingSenderId: '176626384167',
    projectId: 'buccaking-b2542',
    authDomain: 'buccaking-b2542.firebaseapp.com',
    storageBucket: 'buccaking-b2542.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhJJpBVJRl0mKnzF0mvTiNIYZ2kpc932k',
    appId: '1:176626384167:android:8ad7bf17cc1c962bdfbd02',
    messagingSenderId: '176626384167',
    projectId: 'buccaking-b2542',
    storageBucket: 'buccaking-b2542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyWQRxlQDDSaTZjkYeMmtCwG3jDF6nP4',
    appId: '1:176626384167:ios:cfe9480636761a9edfbd02',
    messagingSenderId: '176626384167',
    projectId: 'buccaking-b2542',
    storageBucket: 'buccaking-b2542.firebasestorage.app',
    iosBundleId: 'com.example.buccaKing',
  );
}
